apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: order-generator-lease-holder
  namespace: default
subjects:
  - kind: ServiceAccount
    name: order-generator
    namespace: default
roleRef:
  kind: Role
  name: order-generator-lease-holder
  apiGroup: rbac.authorization.k8s.io
